In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import yaml

In [2]:
dataset1=pd.read_csv('/home/moeen/projects/-Football-Match-Outcome-And-Score-Prediction/data/raw/former_names.csv')

In [6]:
dataset2=pd.read_csv("/home/moeen/projects/-Football-Match-Outcome-And-Score-Prediction/data/raw/goalscorers.csv")
df2=dataset2

In [8]:
dataset3=pd.read_csv("/home/moeen/projects/-Football-Match-Outcome-And-Score-Prediction/data/raw/results.csv")
df3=dataset3

In [7]:
dataset4=pd.read_csv("/home/moeen/projects/-Football-Match-Outcome-And-Score-Prediction/data/raw/shootouts.csv")
df4=dataset4

In [3]:
df1=dataset1

In [4]:
df1.head()

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [9]:
df3.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False